# Generated by Django 4.0.6 on 2022-07-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_available_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
