# Generated by Django 4.0.6 on 2022-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_product_product_available_count_product_product_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
